user <- Sys.getenv("USERNAME")
pkg_path <- function(pkg) sprintf("C:/Users/%s/Downloads/%s", user, pkg)
install.packages(pkg_path("Rcpp_1.0.14.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("tidyverse_2.0.0.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("magrittr_2.0.3.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("ggplot2_3.5.2.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("gtable_0.3.6.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("rlang_1.1.6.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("glue_1.8.0.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("lifecycle_1.0.4.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("scales_1.4.0.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("R6_2.6.1.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("farver_2.1.2.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("RColorBrewer_1.1-3.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("vctrs_0.6.5.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("tibble_3.2.1.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("pillar_1.10.2.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("cli_3.6.5.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("pkgconfig_2.0.3.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("withr_3.0.2.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("tidyr_1.3.1.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("here_1.0.1.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("rprojroot_2.0.4.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("jsonlite_2.0.0.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("openxlsx_4.2.8.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("stringi_1.8.7.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("zip_2.3.3.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("dplyr_1.1.4.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("generics_0.1.4.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("tidyselect_1.2.1.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("purrr_1.0.4.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("readr_2.1.5.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("hms_1.1.3.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("tzdb_0.5.0.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("stringr_1.5.1.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("forcats_1.0.0.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("lubridate_1.9.4.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("timechange_0.3.0.zip"), repos = NULL, type = "binary")
install.packages(pkg_path("fs_1.6.6.zip"), repos = NULL, type = "binary")

library(tidyverse)
library(here)
library(jsonlite)
library(openxlsx)
